### ISSUE TITLE
Product\Collections\StockProcessor::process declaration doesn't match Product\CollectionProcessorInterface in Magento 2.3.2

### ISSUE THREAD

**Issue by taylormodernized** [scandipwa/catalog-graphql#13]
**Describe the bug**
Attempting to get any products through the graphQL endpoint in Magento 2.3.2 fails with the following error message:

```"Fatal Error: 'Declaration of ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Products\\DataProvider\\Product\\CollectionProcessor\\StockProcessor::process($collection, Magento\\Framework\\Api\\SearchCriteriaInterface $searchCriteria, array $attributeNames): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection must be compatible with Magento\\CatalogGraphQl\\Model\\Resolver\\Products\\DataProvider\\Product\\CollectionProcessorInterface::process(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection $collection, Magento\\Framework\\Api\\SearchCriteriaInterface $searchCriteria, array $attributeNames): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection' in '\/var\/www\/vendor\/scandipwa\/catalog-graphql\/src\/Model\/Resolver\/Products\/DataProvider\/Product\/CollectionProcessor\/StockProcessor.php' on line 15"```

**To Reproduce**
1. Load a Product page with catalog-graphql installed on Magento 2.3.2
2. Note the above error message and error 400 from the `/graphql` endpoint

**Expected behavior**
Product listing is returned over the graphql endpoint

**Additional context**
The `ScandiPWA\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CollectionProcessor\StockProcessor::process` `$collection` parameter needs to have `Magento\Catalog\Model\ResourceModel\Product\Collection` specified as the type

**Comment by eli-l** [comment]
Please upgrade to the latest version, it has all the necessary fixes.

**Comment by eli-l** [comment]
Oh I see latest tag has some issues, as it does not contain the latest changes.

**Comment by eli-l** [comment]
Please be sure to use **1.5.2** or **2.0.1** versions.

**Comment by taylormodernized** [comment]
Perfect, Thank you for updating the package!
