### ISSUE TITLE
Search page pagination works incorrectly

### ISSUE THREAD

**Issue by IvansZuks** [scandipwa/catalog-graphql#32]
**Describe the bug**
Last page result show product from the first page instead of correct products

**To Reproduce**
1. Open frontend
2. Try to find something (make sure that you will have 3+ pages result)
3. The last Page has part of first page products

**Expected behavior**
Should be visible last page products

**Additional context**
To fix it remove '-1' from \ScandiPWA\CatalogGraphQl\Model\Resolver\Products\Query\Search:166

**Comment by alfredsgenkins** [comment]
This seem to no longer be the case! Reopen if still true!
