### ISSUE TITLE
Custom Options for product

### ISSUE THREAD

**Issue by mwalol** [scandipwa/catalog-graphql#45]
**Is your feature request related to a problem? Please describe.**
Display Custom Options on Product Listing Page on frontend

**Describe the solution you'd like**
Currently the Custom Options are not Displayed on the Product Listing, even if a product do have them.

**Comment by alfredsgenkins** [comment]
Implemented. Will be released in next 2.x release.

**Comment by sszymkowicz** [comment]
@alfredsgenkins when is it expected for this feature to be released? 
Where can I find the implementation?
