### ISSUE TITLE
Results are not returned in correct sort order

### ISSUE THREAD

**Issue by php4umagento** [scandipwa/catalog-graphql#54]
**Describe the bug**
Search query does return products sorted by ID always

**To Reproduce**
1. Call graphQL to retrieve products by keyword
2. Review that items returned are sorted by product ID

**Expected behavior**
Items should be sorted by relevance DESC when no sort order is specified, or sorted by specified sort attribute and direction

**Additional context**

Catalog Graphql search resolver does 2 queries, where in second query IN is being used to create paginated version of the list.

This slows down the response, and also looses original sorting provided by catalog search engine

https://github.com/scandipwa/catalog-graphql/commit/4ac46b2b406f79e6ee0904dd29bce4180e9cdbf8#diff-115db6f2286ef8033ecac44a4a5a68ff

```
        $filter = $this->filterHelper->generate($idField, 'in', $searchIds);
        $searchCriteria = $this->filterHelper->remove($searchCriteria, 'search_term');
        $searchCriteria = $this->filterHelper->add($searchCriteria, $filter);
        $searchResult = $this->filterQuery->getResult($searchCriteria, $info, true);

        $searchCriteria->setPageSize($realPageSize);
        $searchCriteria->setCurrentPage($realCurrentPage);
        $paginatedProducts = $this->paginateList($searchResult, $searchCriteria);

```

**Comment by alfredsgenkins** [comment]
I think this is no longer the case. Current filter and search query implementations are broad directly from Magento 2.4
