### ISSUE TITLE
Installation failure via composer

### ISSUE THREAD

**Issue by shebin512** [scandipwa/catalog-graphql#61]
**Describe the bug**
scandipwa docker setup installation failure due to exception in composer install of the module scandipwa/catalog-graphql
**To Reproduce**
1. Go to 'https://docs.scandipwa.com/docs/installation/docker/linux/'
2. Follow the steps to install.
3. Check the app container logs 
4. Composer install command throws error. (Please check the attached Screenshot)

**Expected behavior**
Installation should complete without any errors.
**Screenshots**
![image](https://user-images.githubusercontent.com/7988642/83947654-01325e80-a836-11ea-9bb9-4ed3ac75a181.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1 Tessa x86_64
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
Docker development environment setup.

**Comment by iamrolands** [comment]
This has been resolved. Please follow the latest docker setup guide.
