### ISSUE TITLE
Simple Product in a Bundle Product Bug

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/catalog-graphql#67]
**Describe the bug**
If a bundle product has a disabled simple product then there coming a error/Notice in graphql
`Notice: Undefined offset: 6445 in vendor/scandipwa/catalog-graphql/src/Model/Resolver/Links/Collection.php on line 229`

**Test Query**
`
query{
  products(filter: { sku: { eq: "Your SKU"} }){
    items {
	name
     	sku
        ... on BundleProduct {
       	items {
          options {
            price
            id
            product {
	     name
              sku
              price_range {
                  minimum_price {
                    regular_price {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
   }
  }
`

**Comment by teodormoq** [comment]
`getDropdownOptions` in frontend `productBundleItem.container.js` also needs a fix if you choose this solotion
`
getDropdownOptions(values) {
        return values.reduce((acc, {
            id,
            label,
            price_type,
            quantity,
            can_change_quantity,
            product
        }) => {
            if (!product) return null;

            const { price_range: { minimum_price: { regular_price: { value } } } } = product;

            const dropdownLabel = !can_change_quantity
                ? `${ quantity } x ${ label } + ${ this.renderOptionLabel(price_type, value) }`
                : `${ label } + ${ this.renderOptionLabel(price_type, value) }`;

            acc.push({
                id,
                name: label,
                value: id,
                label: dropdownLabel
            });

            return acc;
        }, []);
    }
`

**Comment by teodormoq** [comment]
And renderOptionDropdownValues `if (!dropdownOptions) return null;`

**Comment by alfredsgenkins** [comment]
I think we should somehow ban reporting issues in these repositories, move to mono-repo, otherwise it is too complex to maintain.

**Comment by alfredsgenkins** [comment]
Closing, migrated to theme repo
