### ISSUE TITLE
Array format not correct

### ISSUE THREAD

**Issue by dfelton** [scandipwa/catalog-graphql#70]
**Describe the bug**
Array format returned is not correct in https://github.com/scandipwa/catalog-graphql/blob/c11f4fe9f922b19360646013331d40140c238522/src/Plugin/Resolver/Products/FilterArgument/ProductEntityAttributesForAst.php#L57-L66

**To Reproduce**
- step debug and examine the return result of `ScandiPWA\CatalogGraphQl\Plugin\Resolver\Products\FilterArgument\ProductEntityAttributesForAst::aroundGetEntityAttributes()`

**Expected behavior**
Appended items from `return array_merge(...)` match the format that `\Magento\CatalogGraphQl\Model\Resolver\Products\FilterArgument\ProductEntityAttributesForAst::getEntityAttributes()` returns.

**Additional context**

`\Magento\CatalogGraphQl\Model\Resolver\Products\FilterArgument\ProductEntityAttributesForAst::getEntityAttributes()` returns an array in the following format (example):

```php
return [
    'name' => [
        'type' => 'String',
        'fieldName' => 'name'
    ],
    'price' => [
        'type' => 'String',
        'fieldName' => 'price',
    ],
   // (lots of additional attributes as well...)
];
```

however, within this method, this is called as part of the `array_merge()` parameters: `array_keys($this->additionalAttributes)`, which returns values in the following format:
```php
return [
    0 => 'news_to_date',
    1 => 'category_url_key',
    2 => 'category_url_path',
    3 => 'conditions',
];
```

This causes the around method of this plugin to return an array that does not match what Magento intended. Having a mixture of numeric keys and named keys. 

```php
return [
    'name' => [
        'type' => 'String',
        'fieldName' => 'name'
    ],
    'price' => [
        'type' => 'String',
        'fieldName' => 'price',
    ],
   // (lots of additional attributes as well...)
    0 => 'news_to_date',
    1 => 'category_url_key',
    2 => 'category_url_path',
    3 => 'conditions',
];
```

**Comment by alfredsgenkins** [comment]
I will take a look at this. For some reason it seems to work even-though the format we pass-in is wrong. Thanks for the mention!

**Comment by dfelton** [comment]
@alfredsgenkins hope this helps:

This method returns back to the following: 

`\Magento\Framework\GraphQl\Query\Resolver\Argument\AstConverter::getClausesFromAst()`

This method's logic:

```php
    public function getClausesFromAst(string $fieldName, array $arguments) : array
    {
        $attributes = $this->fieldEntityAttributesPool->getEntityAttributesForEntityFromField($fieldName);
        $conditions = [];
        foreach ($arguments as $argumentName => $argument) {
            if (key_exists($argumentName, $attributes)) {
                $argumentName = $attributes[$argumentName]['fieldName'] ?? $argumentName;
                foreach ($argument as $clauseType => $clause) {
                    if (is_array($clause)) {
                        $value = [];
                        foreach ($clause as $item) {
                            $value[] = $item;
                        }
                    } else {
                        $value = $clause;
                    }
                    $conditions[] = $this->clauseFactory->create(
                        $argumentName,
                        $clauseType,
                        $value
                    );
                }
            } elseif (is_array($argument)) {
                $conditions[] =
                    $this->connectiveFactory->create(
                        $this->getClausesFromAst($fieldName, $argument),
                        $argumentName
                    );
            } else {
                throw new \LogicException('Attribute not found in the visible attributes list');
            }
        }
        return $conditions;
    }
```

- This line: `foreach ($arguments as $argumentName => $argument) {`
  - The value of `$argumentName` is an (in my experience) an argument from the filters of a GraphQL query. 

- Therefore this line: `if (key_exists($argumentName, $attributes)) {`
  - Never causes a match on the added values by ScandiWeb's plugin. 

To be honest, because of this I'm not sure what the purpose of this plugin's `array_keys($this->additionalAttributes)` line is then. I haven't encountered a scenario where it'd be applicable. I only stumbled upon this knowledge while stepping through logic with XDebug for a non-related subject. 

Snapshot if helpful:

![Screenshot from 2020-11-05 09-28-33](https://user-images.githubusercontent.com/2659558/98261783-71aaec00-1f4a-11eb-9038-fb3754e5943f.png)

**Comment by alfredsgenkins** [comment]
I think they changed this in some previous version. At the time we created this plugin, it was generating the attributes of products into GraphQL schema.

This plugin is here, because the day when we created it, Magneto did load attributes in the loop, which caused 20 minutes of wait on large scale projects, where each attribute was processed to be injected into GraphQL schema.

Fixing this plugin will make product attributes available in schema, which will allow to query for custom attributes. As you may see now, news from date is unavailable. This makes it impossible to request the new products, which actually breaks New product widget.

Our QAs reported this today, and it seems, resolving this issue will fix that.

Thanks for your research, I really appreciate it ❤️❤️❤️

**Comment by alfredsgenkins** [comment]
I removed this plugin. Thanks! Patch available in commit https://github.com/scandipwa/catalog-graphql/commit/558966a986ec176182f93afc6ec003f73a021b76.
