### ISSUE TITLE
Problem with search products

### ISSUE THREAD

**Issue by gpifarre** [scandipwa/catalog-graphql#79]
**Search no working. Search always return empty results.**

The query products works fine, in exception when use search parameter, in this case, always returns empty results, no error.

**Graphql call without search:**
![without search](https://user-images.githubusercontent.com/58465647/100990928-bb3f2480-3552-11eb-9a24-322be05ceb05.PNG)

**Graphql call with search parameter**
![con search](https://user-images.githubusercontent.com/58465647/100990963-c5612300-3552-11eb-9f37-a620b867417b.PNG)

**If I do the query to Elastic:**
![queryElastic](https://user-images.githubusercontent.com/58465647/100991034-d742c600-3552-11eb-94c7-ed3d6d936601.PNG)

**Additional context**
Whe are working with 3.2.3 and Magento 2.4.1

**Comment by VuThuan** [comment]
@alfredsgenkins Are you any new ? Thanks

**Comment by alfredsgenkins** [comment]
@lianastaskevica please validate, I have not seen such behavior on QA instances. Maybe create a ticket if issue is indeed reproduce-able?
